name: Atualiza Google Sheets

on:
  schedule:
    - cron: '0 11 * * *'  # Roda todo dia às 08:00 da manhã (horário de Brasília)
  workflow_dispatch:       # Permite rodar manualmente pelo Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instala dependências
        run: |
          pip install -r requirements.txt

      - name: Executa script de atualização
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
          python atualiza_sheets.py
