name: Atualiza Google Sheets

on:
  schedule:
    - cron: '0 13 * * *'  # Roda todo dia às 10h BRT (13 UTC)
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Salvar chave de serviço Google (secreta)
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > credentials.json

      - name: Rodar script de atualização
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json
        run: |
          python atualiza_sheets.py
